springdoc:
  packages-to-scan: com.sc.surveymarket.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true