spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG